### ISSUE TITLE
May it support delete specified diretories or files in the app's diretory?

### ISSUE THREAD

**Issue by dickeylth** [ios-control/ios-deploy#102]
I need to clean up some directories or files before upload files, is it possible to add the feature to the command? Really appreciated!

**Comment by bedaronco** [comment]
I stumbled upon ios-deploy about a week ago and the only thing that wasn't working well for me is that in order to remove a directory you had to clear the directory first.  Which required a new connection for every file and subdirectory.  Which was way too slow for how I'm using this.  

So I made some changes.  I have some local modifications that will empty directories if the path requested for the current --rm option is a directory.  With the changes you could do:

` ios-deploy --bundle_id my.app.whatever --rm /Documents` 

and it will remove everything in the apps Documents directory (not the Documents directory itself though). Or you could do any file or directory that you have a path for.  For how I use it, I call ios-deploy --rm for every file and top level directory in Documents.  The changes I made will go into all subdirectories and empty them out and then remove the subdirectory itself.

I would be happy to share these changes if you want them.

**Comment by shazron** [comment]
Thanks @bedaronco - a pull request is definitely appreciated!

**Comment by headupinclouds** [comment]
@bedaronco : Can you share the changes via PR?  I have a similar need.  Thanks.

**Comment by gabebear** [comment]
Is this related to #420 ?

**Comment by ptc-shunt** [comment]
See #440 (which supersedes #420 )

**Comment by gabebear** [comment]
I belieive this is fixed in #440
