### ISSUE TITLE
Simplify Licensing

### ISSUE THREAD

**Issue by gabebear** [ios-control/ios-deploy#408]
Currently one file(errors.h) is under a different license from the rest of the work.

Having ios-deploy be dual-license creates road-blocks on where it can be used(e.g. having lawyers read custom licenses).

I can see a couple ways to moving to a pure GPLv3 license
 - Get SDMMobileDevice to license errors in GPLv3 @samdmarshall ?
 - Re-extract the error codes/messages.

**Comment by samdmarshall** [comment]
@gabebear hi, could you please elaborate as to what exactly is the issue here and the intended use of the project and related sources where both a GPLv3 license and BSD-3 license are in conflict? As this reads to me, it comes across as a potential commercial application that would then be constrained to the fact that you would have to acknowledge that you are using licensed code? The BSD-3 license is purposely written so you cannot purposely position it commercially as a result of promoting the work of another for your own uses, which seems like it would be more incentive to Not change any license.

I'm not sure where custom licenses come into play, as both licenses attached to this project (GPLv3 and BSD-3 Clause) are fairly well established. I've taken some time to look over the related code and it seems the structure of the `errors.h` file used by this project now differs significantly from my original file (which i believe was in use originally). As it is a derivative work, continuing to attach the license seems appropriate and correct. Speaking for myself and my code, I am not willing to re-license any parts or whole of the work under any other license as that would defeat the original purpose of licensing my project as such. 

My reasoning for this is because I created the SDMMobileDevice project while as a university student and worked on it as part of my senior thesis. All of the work was published openly prior to any submissions to the university, and licensed as such to prevent being used by others (former, then current) professors and department leadership; as well as other developers from using my work without authorization or being appropriately credited for it. I know the value that the work has, and what the risk is by relicensing it under a more commercially permissive license.

---

All that said, I feel a bit weird with regards to singularly asserting my rights regarding a derivative work without input from this project's maintainers and leadership regarding their opinions and thoughts of how this project or a derivative would be used commercially. Although, that seems complicated as the licensed work from me is now very much a derivative work, rather than a stand-alone piece that can be replaced. I think there is very little else that can be said without input from this project's leadership with regards to how they want to move forward with that. If you are using this in a commercial sense, then you can contact me personally regarding my license and derived works and how that impacts you. The SDMMobileDevice project has been used in a commercial product before (with my permission), so if the problem does indeed lie solely with my work then we can see about coming to an arrangement about that (my email is publicly available to drop me a line).

**Comment by samdmarshall** [comment]
@gabebear sorry for this delayed response, but that isn't your problem to fix -- it isn't a problem at all. this is how licensing works, just because it is a minor inconvenience that some company's lawyers have to spend a bit more time sussing out doesn't mean it is a "problem" or needs to be "fixed".
