### ISSUE TITLE
Video tutorial of how to use the ios-deploy app

### ISSUE THREAD

**Issue by hiraditya** [ios-control/ios-deploy#482]
Are there video tutorials to help getting started with the tool. That will help n00bs like me to learn step by step. If there are presentation videos, please provide link to them. Things like:
- Getting started with ios-deploy
- A debugging session with ios-deploy
- Running an xctest

**Comment by gabebear** [comment]
I don't know of any videos.

Is there a reason you are wanting to use ios-deploy directly(instead of Xcode or another IDE)? I _think_ most users of ios-deploy are either automating testing or using it to make their own IDE on top of ios-deploy(either cobbling together a DIY IDE or a full-featured IDE like Cordova/Flutter).

**Comment by hiraditya** [comment]
i want to automate the testing, and do something like randomly clicking on buttons etc. if possible.

**Comment by gabebear** [comment]
If you can, I'd HEAVILY recommend doing as much automated testing as you can on the iOS simulators before thinking about real-device testing. Sometimes real-device testing is needed, but it's far more difficult and frustrating than using the iOS simulators.

ios-deploy doesn't directly give you a way to tap/click on your app or run tests. ios-deploy does allow you to create a lldb debugging session with your app on a real device which you _could_ use to simulate a tap or launch things, but you will need to already know how to do these things via lldb commands/scripts.

Using ios-deploy for testing is not a great beginners project. I think explaining how and why to setup that kind of testing is more suited to a series of blog posts rather than a video.

**Comment by gabebear** [comment]
Closing this, but I do realize that we do need to improve documentation.
