### ISSUE TITLE
Allow server mode for debugserver

### ISSUE THREAD

**Issue by nisargjhaveri** [ios-control/ios-deploy#523]
In debugserver only mode with with `--nolldb`, currently it can accept only one connection. It also does not kill after the connection is closed, leaving ios-deploy still running without any use. This also means that for each external lldb launch, you need to manually kill and restart ios-deploy.

It would be much more convenient if we can allow multiple connection to debugserver in this case.

Alternatively, it can also be useful to simply exit from ios-deploy once the lldb connection is closed as currently it gives no feedback whether the instance is usable or not.

**Comment by ivanhernandez13** [comment]
We would need to first implement automatically exiting ios-deploy when the lldb connection is closed. Once we can do that, adding an additional server mode shouldn't be too difficult, instead of exiting after the lldb connection is closed we would call `start_remote_debug_server()` again.

At the moment there is nothing that tells us when lldb has disconnected, we set up connections to read and send messages but nothing to check when the connection is closed so ios-deploy will run indefinitely with no feedback.

**Comment by gabebear** [comment]
Are we sure you can't reconnect to a debug-server?

It's possible that the client is sending some kind of "kill" command when disconnecting, but I haven't actually looked into this.

**Comment by nisargjhaveri** [comment]
To make it truly effective, we would also need to support simultaneous connections. The approach @ivanhernandez13 mentioned gets us to much better state than what we currently have, but it also limits to one lldb session at a time.

I believe we know at this point that the lldb client connection is gone.
https://github.com/ios-control/ios-deploy/blob/357d1761795eb30c71e14d26ac276dedf31ef6a5/src/ios-deploy/ios-deploy.m#L1105-L1110

**Comment by nisargjhaveri** [comment]
I've tried something in the linked PR. Have a look if it makes sense?
