### ISSUE TITLE
How to attach to running app

### ISSUE THREAD

**Issue by nisargjhaveri** [ios-control/ios-deploy#525]
Sorry for the combination of how to and potential feature request.

I'm having hard time figuring out how to an already running app instance on ios via ios-debug and lldb.

Xcode seems to attach directly to the pid. But I haven't found a way to list PIDs outside of Xcode yet. Is there anything that I can use to list processes running on the device?

Would it be something we'd like to be a part of ios-deploy, which can either list the processes, or simply gives the pid given bundle id or bundle.

**Comment by ivanhernandez13** [comment]
Not sure how to list the processes running on the remote device. I expect that it won't be as easy as connecting to the remote debugserver from a local lldb and running `shell ps` from the lldb command line but I haven't tried it myself.

As for attaching to a running app, you can attach to a running process by name e.g. `process attach --name MyApp`. These instructions should help: https://kov4l3nko.github.io/blog/2016-04-27-debugging-ios-binaries-with-lldb/#starting-debugging

Note that that guide is for jailbroken devices so you won't be able to follow the parts about sshing into the device and attaching by PID but most of the content still applies. Also, you won't be able to attach to apps that you didn't build and install yourself since attaching a debugger requires a special permission that will not be set for other apps.

**Comment by nisargjhaveri** [comment]
For me `process attach --name MyApp` always results in an error similar to "process not found" after doing `process connect...`

Also, interestingly `shell ps` lists processes running on Mac.

**Comment by nisargjhaveri** [comment]
This repository contains code to talk to `com.apple.instruments.remoteserver` service and list out running processes and their pid.

https://github.com/troybowman/ios_instruments_client

Does it make sense to integrate that here to make ios-deploy single-stop solution?

**Comment by nisargjhaveri** [comment]
The new `--list_processes` and `--get_pid` options can help getting the pid for the app. That pid can be later used to attach to the app via lldb and debugserver.
