### ISSUE TITLE
Is there a way to use the debugserver I built?

### ISSUE THREAD

**Issue by rayxia** [ios-control/ios-deploy#546]
Hi, I just want to change the code to replace the system debugserver with mine built by myself (I want to check something). 

I notice the source code uses the apple server "com.apple.debugserver" to launch the debugserver, there is a way to replace it?

**Comment by ivanhernandez13** [comment]
The debugserver executable isn't on the device by default. It is installed onto the device by Xcode or ios-deploy by mounting the image found at `/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/DeviceSupport/15.2/DeveloperDiskImage.dmg`, exact path varies by iOS version. You probably can't simply replace the debugserver in that image and mount it because it almost certainly signed directly by Apple and will fail to mount if the contents are changed. So no, you probably can't install a custom debugserver onto your iOS device. If you're using a jailbroken device then that's a different story and one not covered by this project. Regardless, you probably don't want to use a custom debugserver as it would need to have been built specifically for iOS (as opposed to macOS) and building it for iOS requires including system libraries such as Springboard ([example](https://github.com/apple/llvm-project/blob/7a3e033e1b5fe984a9491988dd2b48b85568e228/lldb/tools/debugserver/source/RNBServices.cpp#L25)) which only Apple engineers have access to.

**Comment by rayxia** [comment]
@ivanhernandez13 OK, thanks for your answer.
