### ISSUE TITLE
ios-deploy with --justlaunch does not work on ipa

### ISSUE THREAD

**Issue by jayshah123** [ios-control/ios-deploy#571]
Include the **command line arguments** you used for ios-deploy.

```
ios-deploy --id 00008030-000C089214E8C02E --bundle ~/mydir/my-app.ipa --justlaunch
```

Don't forget to check out the [README](https://github.com/phonegap/ios-deploy/blob/master/README.md) before filing this issue.

# Expected behavior

App should launch as expected

# Actual behavior.

"Could not read Info.plist"

# Steps to reproduce the problem

Try to install & launch ipa on device.

# System Specs

Please run the commands below in your Terminal.app and include it in the issue. Check when done and include results below.

- [X] 1. system_profiler SPSoftwareDataType
- [x] 2. ios-deploy -V
- [x] 3. xcodebuild -version
- [x] 4. xcode-select --print-path
- [x] 5. gcc --version
- [x] 6. lldb --version
- [x] **If using NodeJS/npm**
  - [x] 7. npm -v
  - [x] 8. node -v
  
 ```
System Software Overview:
System Version: macOS 13.1 (22C65)
Kernel Version: Darwin 22.2.0
Boot Volume: Macintosh HD
Boot Mode: Normal
Computer Name: jayshah’s MacBook Pro
User Name: jayshah (jayshah)
Secure Virtual Memory: Enabled
System Integrity Protection: Enabled
Time since boot: 3 days, 7 hours, 12 minutes
      
ios-deploy version: 1.12.1
      
Xcode 14.0.1
Build version 14A400
/Applications/Xcode-14.0.1.app/Contents/Developer

Gcc versions:
Apple clang version 14.0.0 (clang-1400.0.29.102)
Target: arm64-apple-darwin22.2.0
Thread model: posix
InstalledDir: /Applications/Xcode-14.0.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

lldb versions:
lldb-1400.0.30.3
Apple Swift version 5.7 (swiftlang-5.7.0.127.4 clang-1400.0.29.50)

npm version:
8.15.0

node version:
v16.17.1
```

**Comment by ivanhernandez13** [comment]
It doesn't look like this ever worked since launching the app requires knowing the bundle id and we can only extract the bundle id from the unzipped bundle (i.e. my-app.app not my-app.ipa). The [code](http://github.com/ios-control/ios-deploy/blame/master/src/ios-deploy/ios-deploy.m#L1059) that creates the lldb launch commands hasn't changed since the initial commit.

You can run `unzip my-app.ipa` to unzip it yourself and `my-app.app` will be under the `Payload` directory.

There's probably a way to do this without manually unzip'ing but seeing as there's a workaround I don't think I'll look into this in the near future.

**Comment by jayshah123** [comment]
Makes sense, thanks
